apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    app: nginx
  name: giri-mar1
  project: giri-nov
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: giri-aks
  config:
    kind: aksClusterConfig
    metadata:
      name: giri-mar1
    spec:
      managedCluster:
        apiVersion: "2022-07-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: false
          dnsPrefix: giri-mar1-dns
          enableRBAC: true
          kubernetesVersion: 1.27.7
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
          powerState:
            code: Running
        sku:
          name: Basic
          tier: Free
        tags:
          email: giridharaprasad@rafay.co
          env: qa
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2022-07-01"
        location: centralindia
        name: primary
        properties:
          count: 3
          enableAutoScaling: true
          maxCount: 3
          maxPods: 110
          minCount: 2
          mode: System
          orchestratorVersion: 1.27.7
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B2ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: giri
  type: aks
