apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: p1
  project: giri-nov
spec:
  active: true
  stages:
  - config:
      destinationRepo: {}
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        repository: giri-qc-feb
        revision: main
      systemToGitSync: true
    name: v1
    type: SystemSync
  triggers:
  - config:
      repo:
        provider: Github
        repository: giri-qc-feb
        revision: main
    name: v1
    type: Webhook
