apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    logging: enabled
    rafay.dev/description: ""
  labels:
    env: prod
  name: cloudops
  project: giri-nov
spec:
  limitRange:
    container:
      default:
        cpu: 250u
        memory: 64Ki
      defaultRequest:
        cpu: 250u
        memory: 64Ki
      max:
        cpu: 500u
        memory: 128Ki
      min:
        cpu: 250u
        memory: 64Ki
      ratio:
        cpu: 1
        memory: 1
    pod:
      max:
        cpu: 500u
        memory: 128Ki
      min:
        cpu: 250u
        memory: 64Ki
      ratio:
        cpu: 1
        memory: 1
  namespaceMeshPolicyParams: {}
  networkPolicyParams:
    networkPolicyEnabled: true
    policies:
    - name: ns-p1
      version: v1
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-mar1
  resourceQuotas:
    configMaps: "10"
    cpuLimits: 8000m
    cpuRequests: 4000m
    gpuLimits: "10"
    gpuRequests: "10"
    memoryLimits: 16384Mi
    memoryRequests: 8192Mi
    persistentVolumeClaims: "2"
    pods: "30"
    replicationControllers: "5"
    secrets: "10"
    services: "10"
    servicesLoadBalancers: "4"
    servicesNodePorts: "4"
    storageRequests: 10Gi
