apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: cb-test
  description: cb-test
  labels:
    env: qa
  name: redis-cb
  project: giri-nov
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  networkPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-az1
    - key: rafay.dev/clusterName
      value: giri-jan29
    - key: rafay.dev/clusterName
      value: giri-jun31
  resourceQuotas:
    configMaps: "5"
    pods: "10"
    secrets: "5"
    services: "5"
