apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx
  project: giri-nov
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/nginx/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: feb291
  placement:
    selector: rafay.dev/clusterName=giri-feb28-az1
  version: nginx-v1-202402281108050000
