apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    chart: prometheus-11.0.2
    component: alertmanager
    custom-app: alert-man
    heritage: Helm
    release: rafay-prometheus
  name: custom-configmap-alertmanager
