apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: giri-qc-feb
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAtJ00XymY0+nHfqwmOzdu7QW22o6JPr8LkpSYWzZ8Fun8bulDHylqWf2xO45Mb6gJEPXZB479St+Zr1zMMfOnLvEbDWUfs1BlGV9GDtosgnjUzOjV17ft6t4QuJSi6CajGd+yqkGwKnCf5zYfCD4CbQBMqUnNVQaAbDypEfCrXH+KjrFHMBySzMT+n01YBYjtVZeCI1TYWt4IvR/oyrc/r9Kh2RAnFlPOuSge5g6gjp8vQalVFq9y0nar3ufbDHdcWVSFUg/Mx7x49ap4SgQFAK4OmQdyscm3mRnzba5oNDe67jv8M6IETl70QnqolIDPMuG5Iwb15wbtXTVSf6c6n8y/tNqjxfvi24vWVpI0fHz3md6X3gZbxe6OLvC9pEWP9zRn1Dyffq/y3vbFkO2jDTaghjRnNHzk=
  template:
    metadata:
      creationTimestamp: null
      name: giri-qc-feb
      namespace: default

