apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-managed2
  project: giri-nov
spec:
  base:
    name: default-aks
    version: 2.3.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  type: custom
  version: v1
