apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: feb-cb1
  project: giri-nov
spec:
  base:
    name: feb-gb1
    version: version1
  customAddons:
  - name: redis1
    version: redis-v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  type: custom
  version: v1
