apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: giri-qc-feb
  project: giri-nov
spec:
  agents:
  - name: giri-mar1
  credentials:
    password: sealed://credentials.password
    username: giri-rafay
  endpoint: https://github.com/giri-rafay/giri-qc-feb.git
  secret:
    name: file://artifacts/giri-qc-feb/sealed-secret.yaml
  type: Git
